language: node_js
node_js:
  - '0.10'
before_install:
  # preprod auto-deploy key for "real" pushes (not for pull requests). http://docs.travis-ci.com/user/encrypting-files/
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_9c67d478eacb_key -iv $encrypted_9c67d478eacb_iv -in devkeys/swarmsim-preprod.pem.enc -out devkeys/swarmsim-preprod.pem -d'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && chmod 600 devkeys/swarmsim-preprod.pem'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && eval `ssh-agent`'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ssh-add devkeys/swarmsim-preprod.pem'
  # --global required because grunt-gh-pages uses a new repo to push
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && git config --global user.name '
  # rot13 email, because spam
  - "[ '${TRAVIS_PULL_REQUEST}' = 'false' ] && git config --global user.email "
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && GIT_AUTHOR_NAME="Evan Rosson (via travis-ci.org robots)" GIT_AUTHOR_EMAIL=`echo "genivf-pv@fjnezfvz.pbz" | tr "[A-Za-z]" "[N-ZA-Mn-za-m]"` grunt deploy-preprod-building'
  # done with preprod setup
  - 'gem install compass'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && GIT_AUTHOR_NAME="Evan Rosson (via travis-ci.org robots)" GIT_AUTHOR_EMAIL=`echo "genivf-pv@fjnezfvz.pbz" | tr "[A-Za-z]" "[N-ZA-Mn-za-m]"` grunt deploy-preprod'
