language: node_js
node_js:
  - '0.10'
before_install:
  - 'gem install compass'
  # preprod auto-deploy key. http://docs.travis-ci.com/user/encrypting-files/
  - 'openssl aes-256-cbc -K $encrypted_9c67d478eacb_key -iv $encrypted_9c67d478eacb_iv -in devkeys/swarmsim-preprod.pem.enc -out devkeys/swarmsim-preprod.pem -d'
  - 'chmod 600 devkeys/swarmsim-preprod.pem'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
after_success:
  - 'ssh-add devkeys/swarmsim-preprod.pem'
  - 'grunt deploy-preprod'
